
#  See https://github.com/flatpak/flatpak-github-actions

name: Build Flatpaks

on:
    workflow_dispatch:          # Manually

jobs:
    flatpak-jrpn16:
        name: "Flatpak JRPN16"
        container:
            image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
            options: --privileged
        strategy:
            matrix:
                variant:
                  - arch: x86_64
                    runner: ubuntu-26.04
                  - arch: aarch64
                    runner: ubuntu-26.04-arm
        runs-on: ${{ matrix.variant.runner }}
        steps:
        - uses: actions/checkout@v6
        - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
          with:
              bundle: jrpn16-${{ matrix.variant.arch }}.flatpak
              manifest-path: jrpn16/flatpak/generated/com.jovial.jrpn16.yml
              arch:  ${{ matrix.variant.arch }}

    flatpak-jrpn15:
        name: "Flatpak JRPN15"
        container:
            image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
            options: --privileged
        strategy:
            matrix:
                variant:
                  - arch: x86_64
                    runner: ubuntu-26.04
                  - arch: aarch64
                    runner: ubuntu-26.04-arm
        runs-on: ${{ matrix.variant.runner }}
        steps:
        - uses: actions/checkout@v6
        - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
          with:
              build-dir: flatpak_app_15
              repo-dir: repo_15
              state-dir: .flatpak-builder_15
              bundle: jrpn15-${{ matrix.variant.arch }}.flatpak
              manifest-path: jrpn15/flatpak/generated/com.jovial.jrpn15.yml
              arch:  ${{ matrix.variant.arch }}
