
# See https://github.com/subosito/flutter-action

name:  Build flatpaks
run-name: ${{ github.actor }} Build flatpaks
on: 
    workflow_dispatch:          # Manually

jobs:
    flatpak-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: subosito/flutter-action@v2
              with:
                  channel: 'stable'
                  # flutter:version: '3.0.0'
            - name: Build JRPN16
              run: |
                dart pub global activate flutpak
                ~/.pub-cache/bin/flubpak flutpak.yaml
                cd jrpn16
            - uses: ./.github/workflows/lib/build_flatpak.yaml
              with:
                manifest: jrpn16/flatpak/generated/com.jovial.jrpn16.yml
                app-id: com.jovial.jrpn16
                arch: x86_64
                artifact_name: jrpn16_x86_64.flatpak
