
# See https://github.com/subosito/flutter-action

name:  Build flatpaks
run-name: ${{ github.actor }} Build flatpaks
on: 
    workflow_dispatch:          # Manually

jobs:
    jrpn16-x86:
        runs-on: ubuntu-26.04
        steps:
            - uses: ./.github/workflows/lib/build_flatpaks
            - with:
                arch: x86_64

#    jrpn16-arm:
#        runs-on: ubuntu-26.04-arm
#        steps:
#            uses: ./.github/workflows/lib/build_flatpak
#            with:
#                calculator:  jrpn16
#                arch: aarch64

